### PR TITLE
Fix typo in dhcp.go

### PR DESCRIPTION
**Pull request by eltociear**
**What this PR does / why we need it**:

**Special notes for your reviewer**:

availble -> available

### CODE REVIEW

**Review by mouuii — APPROVED** [review]

**Comment by mouuii** [comment]
please first read our [contributor.md](https://github.com/nocalhost/nocalhost/blob/main/CONTRIBUTING.md) , the DCO failed

**Comment by eltociear** [comment]
@mouuii Thanks review!
I added a signature to the commit.

**Comment by wencaiwulue** [comment]
please commit from your branch into dev, not main

**Comment by eltociear** [comment]
@wencaiwulue  Thanks! I created new PR.

**Pull request merged**
