### PR TITLE
fix word spelling

### PR DESCRIPTION
**Pull request by mouuii**
Signed-off-by: mouuii <zhouchengbin@koderover.com>

### CODE REVIEW

**Review by anurnomeru — APPROVED** [review]
LGTM

**Comment by anurnomeru** [comment]
Don’t merge for now and we will merge it to the dev branch later

**Comment by mouuii** [comment]
ok , wish to do more

**Comment by mouuii** [comment]
// Check whether the target resoured need to be mutated  

also find this annotation in code , does "resoured" should be replaced with "resource"
@ @anurnomeru

**Comment by anurnomeru** [comment]
> ok , wish to do more

Submit to this branch(mouuii:mouuii-dev) directly, 👍

**Pull request merged**
