### PR TITLE
Add changelog 

### PR DESCRIPTION
**Pull request by neaped**

### CODE REVIEW

**Comment by neaped** [comment]
Add WeChat Group Info

**Comment by neaped** [comment]
Add WeChat group image

**Review by anurnomeru — APPROVED** [review]
LGTM

**Review by anurnomeru — APPROVED** [review]
LGTM

**Review by anurnomeru — APPROVED** [review]
LGTM

**Review by anurnomeru — APPROVED** [review]
LGTM

**Review by anurnomeru — APPROVED** [review]
LGTM

**Comment by neaped** [comment]
Update 0.4.4 changelog

**Pull request merged**
